CREATE TABLE [dbo].[class] (
    [classid] VARCHAR (50) NOT NULL PRIMARY KEY,
	[class_name] VARCHAR(50) NOT NULL,
	[class_section] VARCHAR(30) NOT NULL,
    [s01]     VARCHAR (50) NULL,
    [s02]     VARCHAR (50) NULL,
    [s03]     VARCHAR (50) NULL,
    [s04]     VARCHAR (50) NULL,
    [s05]     VARCHAR (50) NULL,
    [s06]     VARCHAR (50) NULL,
    [s07]     VARCHAR (50) NULL,
    [s08]     VARCHAR (50) NULL,
    [s09]     VARCHAR (50) NULL,
    [s10]     VARCHAR (50) NULL, 
	[update_time] DATETIME NOT NULL,
    [updated_by]          VARCHAR (50)  NOT NULL,
    CONSTRAINT [FK_class_to_admin_manager] FOREIGN KEY ([updated_by]) REFERENCES [dbo].[admin_manager] ([userid]),
    CONSTRAINT [FK_class_to_subject01] FOREIGN KEY ([s01]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject02] FOREIGN KEY ([s02]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject03] FOREIGN KEY ([s03]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject04] FOREIGN KEY ([s04]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject05] FOREIGN KEY ([s05]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject06] FOREIGN KEY ([s06]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject07] FOREIGN KEY ([s07]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject08] FOREIGN KEY ([s08]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject09] FOREIGN KEY ([s09]) REFERENCES [subjects]([subject_code]),
    CONSTRAINT [FK_class_to_subject10] FOREIGN KEY ([s10]) REFERENCES [subjects]([subject_code]),
);