CREATE TABLE [dbo].[fees_structure]
(
	[fees_structure_id] VARCHAR(50) NOT NULL PRIMARY KEY,
	[unit_id01] VARCHAR(50),
	[unit_id02] VARCHAR(50),
	[unit_id03] VARCHAR(50),
	[unit_id04] VARCHAR(50),
	[unit_id05] VARCHAR(50),
	[unit_id06] VARCHAR(50),
	[unit_id07] VARCHAR(50),
	[unit_id08] VARCHAR(50),
	[unit_id09] VARCHAR(50),
	[unit_id10] VARCHAR(50), 
    [creation_time] DATETIME NULL,
    [created_by] VARCHAR (50) NULL,
    CONSTRAINT [FK_fees_structure_to_admin_manager] FOREIGN KEY ([created_by]) REFERENCES [dbo].[admin_manager] ([userid]),
    CONSTRAINT [FK_fees_structure_to_fees_unit01] FOREIGN KEY ([unit_id01]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit02] FOREIGN KEY ([unit_id02]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit03] FOREIGN KEY ([unit_id03]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit04] FOREIGN KEY ([unit_id04]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit05] FOREIGN KEY ([unit_id05]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit06] FOREIGN KEY ([unit_id06]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit07] FOREIGN KEY ([unit_id07]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit08] FOREIGN KEY ([unit_id08]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit09] FOREIGN KEY ([unit_id09]) REFERENCES [fees_unit]([unit_id]),
    CONSTRAINT [FK_fees_structure_to_fees_unit10] FOREIGN KEY ([unit_id10]) REFERENCES [fees_unit]([unit_id]),
);