CREATE TABLE [dbo].[marksheet] 
(
	[marksheet_id] VARCHAR(50) PRIMARY KEY,
    [students_reg_id]   VARCHAR (50)  NOT NULL,
	[classid]   VARCHAR (50)  NOT NULL,
	[class_name] VARCHAR(50) NOT NULL,
	[class_section] VARCHAR(30) NOT NULL,
	[session] VARCHAR(4) NOT NULL,
	[term] VARCHAR(2) NOT NULL,
	[subject_code] VARCHAR(50) NOT NULL,
	[subject_name] VARCHAR(50) NOT NULL,
	[full_marks_written] DECIMAL(3,2),
	[marks_obtained_written] DECIMAL(3,2),
	[full_marks_oral] DECIMAL(3,2),
	[marks_obtained_oral] DECIMAL(3,2),
	[full_marks_practical] DECIMAL(3,2),
	[marks_obtained_practical] DECIMAL(3,2),
	[grade] VARCHAR(2),
    [update_time] DATETIME      NULL,
    [updated_by] VARCHAR (50)  NULL,
    CONSTRAINT [FK_marksheet_to_students] FOREIGN KEY ([students_reg_id]) REFERENCES [dbo].[students] ([students_reg_id]),
    CONSTRAINT [FK_marksheet_to_fees_structure_id] FOREIGN KEY ([classid]) REFERENCES [dbo].[class] ([classid]),
	CONSTRAINT [FK_marksheet_to_admin_manager] FOREIGN KEY ([updated_by]) REFERENCES [admin_manager]([userid]),
);
