CREATE TABLE [dbo].[students]
(
	[students_reg_id] VARCHAR(50) NOT NULL PRIMARY KEY,
	[name] VARCHAR(MAX) NOT NULL,
	[father_name] VARCHAR(MAX),
	[mother_name] VARCHAR(MAX),
	[guardian_name] VARCHAR(MAX) NOT NULL,
	[local_address] VARCHAR(MAX) NOT NULL,
	[parmanent_address] VARCHAR(MAX),
	[guardian_con_no] VARCHAR(20),
	[contact_no] VARCHAR(20),
	[father_con_no] VARCHAR(20),
	[mother_con_no] VARCHAR(20),
	[email_id] VARCHAR(MAX),
	[blood_group] VARCHAR(15),
	[admission_date] DATETIME,
    [status]            VARCHAR (MAX) NULL,
    [tc_from]             VARCHAR (50)  NULL,
    [tc]                VARCHAR (3)   NULL,
    [tc_to]             VARCHAR (50)  NULL,
    [update_time]      DATETIME      NULL,
    [updated_by]        VARCHAR (50)  NULL,
    CONSTRAINT [FK_students_to_admin_manager] FOREIGN KEY ([updated_by]) REFERENCES [admin_manager]([userid]),
);